export const ZIP_CHANGE_REQUEST = 'ZIP_CHANGE_REQUEST'
export const ZIP_CHANGE_SUCCESS = 'ZIP_CHANGE_SUCCESS'
export const ZIP_CHANGE_FAIL = 'ZIP_CHANGE_FAIL'

export const PRODUCTS_ADD_PRODUCT = 'PRODUCTS_ADD_PRODUCT'
